language: node_js

services:
  - mysql

before_script:
  - mysql -e "create database \`qails\`;" -uroot

node_js:
  - "7"
  - "8"

after_success:
  - mysql --version
  - npm run coveralls

sudo: false

# notifications:
#   email: false
